global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vanguard'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /metrics

  - job_name: 'minos'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: /metrics

  - job_name: 'sisyphus'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: /metrics

  - job_name: 'horus'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: /metrics
