global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vanguard'
    static_configs:
      - targets: ['vanguard:8080']
    metrics_path: /metrics

  - job_name: 'minos'
    static_configs:
      - targets: ['minos:9091']
    metrics_path: /metrics
